import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 1600 }, deviceScaleFactor: 2 });
await p.goto("file:///Users/auntlee/workspace/intel-engine/field/reports/fde-report-2026-08-12.html");
await p.waitForTimeout(600);
await p.screenshot({ path: "shots/r1-判断页.png" });
await p.locator("#shape").scrollIntoViewIfNeeded();
await p.waitForTimeout(300);
await p.screenshot({ path: "shots/r2-结构画像.png" });
await p.locator("#cards").scrollIntoViewIfNeeded();
await p.waitForTimeout(300);
await p.screenshot({ path: "shots/r3-名单收起.png" });
await b.close();
